spring:
  application:
    name: cardorders
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console.enabled: true
    sql:
      init:
        schema-locations: classpath:migrations/create_order_table.sql, classpath:migrations/create_listing_table.sql

